version: '3'

services:
  flask:
    container_name: flask
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
    volumes: 
      - ./app/pyapp:/usr/src/app/
      - ./app/pyapp/templates:/usr/src/app/templates
    restart: always
    tty: true


  db:
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: tmcit
      MYSQL_DATABASE: tvice
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/initdb.d/:/docker-entrypoint-initdb.d
#    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci   
    ports:
      - 3306:3306

  nginx:
    container_name: nginx
    image: nginx:latest
    ports: 
      - 80:80
    volumes: 
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    tty: true
