version: '3'

services:
  flask:
    container_name: flask
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
#    volumes: 
#      - ./app:/app
    restart: always
    tty: true


  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports: 
      - 3306:3306
    volumes: 
      - ./db/data:/var/lib/mariadb
    restart: always
    tty: true
    environment:
      MARIADB_ROOT_PASSWORD: tmcit
      MARIADB_DATABASE: tvice
      MARIADB_USER: docker
      MARIADB_PASSWORD: docker
      TZ: 'Asia/Tokyo'

  nginx:
    container_name: nginx
    image: nginx:latest
    ports: 
      - 80:80
    volumes: 
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    tty: true


